{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "234bac21_a48f96c4",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 10
      },
      "lineNbr": 0,
      "author": {
        "id": 667
      },
      "writtenOn": "2024-07-25T23:03:43Z",
      "side": 1,
      "message": "The last error is unrelated to the change, the problem happened after the AI job succeeded and the control-plane-example was going to be scheduled but it couldn\u0027t.",
      "revId": "23542eb391bd2db09d8db219b878aec75769db3b",
      "serverId": "6c1dc8ef-8b94-40e4-bd83-c2359d45ecc0"
    }
  ]
}